// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFyKInO11ZjGE9YZWi12Buddbzjgu7W9s',
    appId: '1:249062701794:web:43381cbbd51dbe8a33fcbb',
    messagingSenderId: '249062701794',
    projectId: 'first-project-a9ed0',
    authDomain: 'first-project-a9ed0.firebaseapp.com',
    storageBucket: 'first-project-a9ed0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRu0zpNTP90ZdBFX6KYbilF6RFtLQWHXQ',
    appId: '1:249062701794:android:7af28cda08d1d75233fcbb',
    messagingSenderId: '249062701794',
    projectId: 'first-project-a9ed0',
    storageBucket: 'first-project-a9ed0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1J8BSeV8Nqgvp-8IXG3uGhhs-oHgTwYg',
    appId: '1:249062701794:ios:813de8672c29f4d933fcbb',
    messagingSenderId: '249062701794',
    projectId: 'first-project-a9ed0',
    storageBucket: 'first-project-a9ed0.firebasestorage.app',
    iosBundleId: 'com.example.stackedApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1J8BSeV8Nqgvp-8IXG3uGhhs-oHgTwYg',
    appId: '1:249062701794:ios:813de8672c29f4d933fcbb',
    messagingSenderId: '249062701794',
    projectId: 'first-project-a9ed0',
    storageBucket: 'first-project-a9ed0.firebasestorage.app',
    iosBundleId: 'com.example.stackedApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3q8Khb9FygpPRybCd5uO3YRdDeTKC9Jk',
    appId: '1:249062701794:web:90cbf81162f1528733fcbb',
    messagingSenderId: '249062701794',
    projectId: 'first-project-a9ed0',
    authDomain: 'first-project-a9ed0.firebaseapp.com',
    storageBucket: 'first-project-a9ed0.firebasestorage.app',
  );
}
